### ISSUE TITLE
JSON-Type for command-topics

### ISSUE THREAD

**Issue by Ranlvor** [uwap/mqtt-control-map#101]
A JSON-Type for command-topics would be nice to control zigbee2mqtt.

Example status message which can be parsed via JSON-Type:
`{"state":"ON","linkquality":34,"brightness":1,"color_temp":454,"color_mode":2,"color":{"x":0.46,"y":0.411}}`

Example command message which can currently not be expressed without a function:
`{"brightness": 200}`

**Comment by uwap** [comment]
Please use `import {json} from "config/types` https://github.com/uwap/mqtt-control-map/blob/master/src/config/types.js#L7

**Comment by uwap** [comment]
nvm, I'm stupid
